version: '3.9'
services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    links:
      - dbmongo
  dbmongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=joaco
      - MONGO_INITDB_ROOT_PASSWORD=joaco

